[project]
name = "thulibfront"
version = "0.1.0"
description = "convenient access to THU's library seat booking system"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.3",
    "selenium>=4.29.0",
    "snoop>=0.6.0",
    "webdriver-manager>=4.0.2",
]
